# Load data

In [626]:
import pandas as pd

df = pd.read_csv("../data/fake_job_postings.csv")

# EDA

## Checking columns

In [627]:
df.columns

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent'],
      dtype='object')

## Checking nan

In [ ]:
df.isnull().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

In [629]:
df = df.dropna(subset=['industry'])

## Checking duplicates

In [630]:
df.duplicated().sum()

np.int64(0)

## Checking unique values

In [631]:
df.industry.value_counts()

industry
Information Technology and Services    1734
Computer Software                      1376
Internet                               1062
Marketing and Advertising               828
Education Management                    822
                                       ...
Sporting Goods                            1
Museums and Institutions                  1
Shipbuilding                              1
Alternative Dispute Resolution            1
Ranching                                  1
Name: count, Length: 131, dtype: int64

In [632]:
df['industry'].nunique()

131

In [633]:
df['industry'].unique()

array(['Marketing and Advertising', 'Computer Software',
       'Hospital & Health Care', 'Online Media',
       'Information Technology and Services', 'Financial Services',
       'Management Consulting', 'Events Services', 'Internet',
       'Facilities Services', 'Consumer Electronics',
       'Telecommunications', 'Consumer Services', 'Construction',
       'Oil & Energy', 'Education Management', 'Building Materials',
       'Banking', 'Food & Beverages', 'Food Production',
       'Health, Wellness and Fitness', 'Insurance', 'E-Learning',
       'Cosmetics', 'Staffing and Recruiting',
       'Venture Capital & Private Equity', 'Leisure, Travel & Tourism',
       'Human Resources', 'Pharmaceuticals', 'Farming', 'Legal Services',
       'Luxury Goods & Jewelry', 'Machinery', 'Real Estate',
       'Mechanical or Industrial Engineering',
       'Public Relations and Communications', 'Consumer Goods',
       'Medical Practice', 'Electrical/Electronic Manufacturing',
       'Hospitality', 'Music', 'Market Research', 'Automotive',
       'Philanthropy', 'Utilities', 'Primary/Secondary Education',
       'Logistics and Supply Chain', 'Design', 'Gambling & Casinos',
       'Accounting', 'Environmental Services', 'Mental Health Care',
       'Investment Management', 'Apparel & Fashion', 'Media Production',
       'Publishing', 'Medical Devices', 'Information Services', 'Retail',
       'Sports', 'Computer Games', 'Chemicals', 'Aviation & Aerospace',
       'Business Supplies and Equipment', 'Program Development',
       'Computer Networking', 'Biotechnology',
       'Civic & Social Organization', 'Religious Institutions',
       'Warehousing', 'Airlines/Aviation', 'Writing and Editing',
       'Restaurants', 'Outsourcing/Offshoring',
       'Transportation/Trucking/Railroad', 'Wireless',
       'Investment Banking', 'Nonprofit Organization Management',
       'Libraries', 'Computer Hardware', 'Broadcast Media', 'Printing',
       'Graphic Design', 'Entertainment', 'Wholesale', 'Research',
       'Animation', 'Government Administration', 'Capital Markets',
       'Computer & Network Security', 'Semiconductors',
       'Security and Investigations', 'Architecture & Planning',
       'Maritime', 'Fund-Raising', 'Higher Education',
       'Renewables & Environment', 'Motion Pictures and Film',
       'Law Practice', 'Government Relations', 'Packaging and Containers',
       'Sporting Goods', 'Mining & Metals', 'Import and Export',
       'International Trade and Development',
       'Professional Training & Coaching', 'Textiles',
       'Commercial Real Estate', 'Law Enforcement',
       'Package/Freight Delivery', 'Translation and Localization',
       'Photography', 'Industrial Automation', 'Wine and Spirits',
       'Public Safety', 'Civil Engineering', 'Military',
       'Defense & Space', 'Veterinary', 'Executive Office',
       'Performing Arts', 'Individual & Family Services', 'Public Policy',
       'Nanotechnology', 'Museums and Institutions', 'Fishery',
       'Plastics', 'Furniture', 'Shipbuilding',
       'Alternative Dispute Resolution', 'Ranching'], dtype=object)

# Prepare data

## Selecting most popular industries

In [634]:
top10 = df['industry'].value_counts().head(10).index

df = df[df['industry'].isin(top10)]

In [635]:
df['industry'].nunique()

10

In [636]:
df

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0
8,9,HP BSM SME,"US, FL, Pensacola",NaN,NaN,Solutions3 is a woman-owned small business who...,Implementation/Configuration/Testing/Training ...,MUST BE A US CITIZEN.An active TS/SCI clearanc...,NaN,0,1,1,Full-time,Associate,NaN,Information Technology and Services,NaN,0
9,10,Customer Service Associate - Part Time,"US, AZ, Phoenix",NaN,NaN,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 6 months custo...,NaN,0,1,0,Part-time,Entry level,High School or equivalent,Financial Services,Customer Service,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17872,17873,Product Manager,"US, CA, San Francisco",Product Development,NaN,Flite delivers ad innovation at scale to the w...,Flite's SaaS display ad platform fuels the wor...,BA/BS in Computer Science or a related technic...,Competitive baseAttractive stock option planMe...,0,1,0,Full-time,NaN,NaN,Internet,Product Management,0
17874,17875,JavaScript Developer,"US, ,",NaN,80000-100000,NaN,"Sr, JavaScript Developer Experience : 4-10 yea...",NaN,NaN,0,0,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Information Technology,0
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0

## Get rid of fake job postings

In [637]:
df = df[df['fraudulent'] == 0]

In [638]:
df.dropna(subset=['description'])

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0
8,9,HP BSM SME,"US, FL, Pensacola",NaN,NaN,Solutions3 is a woman-owned small business who...,Implementation/Configuration/Testing/Training ...,MUST BE A US CITIZEN.An active TS/SCI clearanc...,NaN,0,1,1,Full-time,Associate,NaN,Information Technology and Services,NaN,0
9,10,Customer Service Associate - Part Time,"US, AZ, Phoenix",NaN,NaN,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 6 months custo...,NaN,0,1,0,Part-time,Entry level,High School or equivalent,Financial Services,Customer Service,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17872,17873,Product Manager,"US, CA, San Francisco",Product Development,NaN,Flite delivers ad innovation at scale to the w...,Flite's SaaS display ad platform fuels the wor...,BA/BS in Computer Science or a related technic...,Competitive baseAttractive stock option planMe...,0,1,0,Full-time,NaN,NaN,Internet,Product Management,0
17874,17875,JavaScript Developer,"US, ,",NaN,80000-100000,NaN,"Sr, JavaScript Developer Experience : 4-10 yea...",NaN,NaN,0,0,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Information Technology,0
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0

In [ ]:
df['word_count'] = df['description'].apply(lambda x: len(str(x).split()))
df['word_count'].describe()

C:\Users\Павел\AppData\Local\Temp\ipykernel_17228\3345788944.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['word_count'] = df['description'].apply(lambda x: len(str(x).split()))

count    7758.000000
mean      171.407579
std       119.223345
min         1.000000
25%        88.000000
50%       152.000000
75%       226.000000
max      2115.000000
Name: word_count, dtype: float64

min and max look not good so i will drop them

In [640]:
low = df['word_count'].quantile(0.01)
high = df['word_count'].quantile(0.99)

In [641]:
df = df[(df['word_count'] >= low) & (df['word_count'] <= high)]
df

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,word_count
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,315
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,346
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,168
9,10,Customer Service Associate - Part Time,"US, AZ, Phoenix",NaN,NaN,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 6 months custo...,NaN,0,1,0,Part-time,Entry level,High School or equivalent,Financial Services,Customer Service,0,150
10,11,ASP.net Developer Job opportunity at United St...,"US, NJ, Jersey City",NaN,100000-120000,NaN,Position : #URL_86fd830a95a64e2b30ceed829e63fd...,Position : #URL_86fd830a95a64e2b30ceed829e63fd...,Benefits - FullBonus Eligible - YesInterview T...,0,0,0,Full-time,Mid-Senior level,Bachelor's Degree,Information Technology and Services,Information Technology,0,323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17872,17873,Product Manager,"US, CA, San Francisco",Product Development,NaN,Flite delivers ad innovation at scale to the w...,Flite's SaaS display ad platform fuels the wor...,BA/BS in Computer Science or a related technic...,Competitive baseAttractive stock option planMe...,0,1,0,Full-time,NaN,NaN,Internet,Product Management,0,162
17874,17875,JavaScript Developer,"US, ,",NaN,80000-100000,NaN,"Sr, JavaScript Developer Experience : 4-10 yea...",NaN,NaN,0,0,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Information Technology,0,59
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0,226
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0,161
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0,328

In [642]:
df.iloc[4]['description']

"Position : #URL_86fd830a95a64e2b30ceed829e63fd384c289e4f01e3c93608b42a84f6e662dd# DeveloperJob Location :United States-New Jersey-Jersey CityUs work status required : EAD / Green Card / US Citizens Detailed Description#URL_86fd830a95a64e2b30ceed829e63fd384c289e4f01e3c93608b42a84f6e662dd# Developer with strong SQL &amp; VB.NET working in a highly effective software development team responsible for development of and enhancements to our IDB reporting and billing systems. All work efforts will be performed according to policies and procedures relating to software development and quality.Background: Developer with 5+ years of development experience using #URL_86fd830a95a64e2b30ceed829e63fd384c289e4f01e3c93608b42a84f6e662dd#, VB.NET, including 3-5 years in SQL development.Required:• College degree• Experience building web based applications using #URL_86fd830a95a64e2b30ceed829e63fd384c289e4f01e3c93608b42a84f6e662dd# and SQL Server.• Expert level, hands-on experience writing SQL Server Stored Procedures.• Proficient in MS Office products (Excel, Access, Word, Outlook)• Worked in a role that involved the creation of reports for internal management and/or external customers.• Experience developing in another scripting/front-end language.• Excellent communication skillsIf you are interested, please send your updated profile to #EMAIL_897dfb1f33f6c34f2bed521623e9808aa4e62d89a6c0284cfe89393e4457e628#Hiring for Sales Account Director(advertising/digital sales)Position : Sales Account Director - Pacific NorthwestJob Location : United States,Washington-SeattleUs work status required : EAD / Green Card / US Citizens Requirements :•3+ years of advertising/digital sales experience, preferrably in the region•Ability to provide forecasting information to management•Proven success prospecting/cold-calling regional accounts•Proven experience in automotive, tech, health care, and travel categories, among others•Specialized experience with hands-on agency account management •Self-starter with a roll-up-your-sleeves mentality•Ability to work with the internal teams to solve problems•Solid grasp of interactive media, including various pricing models, targeting technologies, and ad serving•Bachelor's degree•Strong long-distance communication skills using email, instant messenger platforms, and phone•High technical aptitude for learning and working within desktop and web-based applications (Windows, Microsoft Office, DSPs, ad exchanges) •Ability to calculate and analyze data based on standard digital advertising cost-per metrics (CPM, CPC, CPA, etc.)•Detail-oriented with strong organizational skills and multitasking ability•Ability to work efficiently and effectively under tight deadlines; strong sense of urgency•Personality to work effectively within a fast-moving environment and with many different types of people•Desire and ability to work from home\xa0"

maybe delete URL

In [643]:
import re

def remove_url_tokens(text):
    return re.sub(r'#URL_[A-Za-z0-9]+#', '', text)

df['description'] = df['description'].apply(remove_url_tokens)
df.iloc[4]['description']

"Position :  DeveloperJob Location :United States-New Jersey-Jersey CityUs work status required : EAD / Green Card / US Citizens Detailed Description Developer with strong SQL &amp; VB.NET working in a highly effective software development team responsible for development of and enhancements to our IDB reporting and billing systems. All work efforts will be performed according to policies and procedures relating to software development and quality.Background: Developer with 5+ years of development experience using , VB.NET, including 3-5 years in SQL development.Required:• College degree• Experience building web based applications using  and SQL Server.• Expert level, hands-on experience writing SQL Server Stored Procedures.• Proficient in MS Office products (Excel, Access, Word, Outlook)• Worked in a role that involved the creation of reports for internal management and/or external customers.• Experience developing in another scripting/front-end language.• Excellent communication skillsIf you are interested, please send your updated profile to #EMAIL_897dfb1f33f6c34f2bed521623e9808aa4e62d89a6c0284cfe89393e4457e628#Hiring for Sales Account Director(advertising/digital sales)Position : Sales Account Director - Pacific NorthwestJob Location : United States,Washington-SeattleUs work status required : EAD / Green Card / US Citizens Requirements :•3+ years of advertising/digital sales experience, preferrably in the region•Ability to provide forecasting information to management•Proven success prospecting/cold-calling regional accounts•Proven experience in automotive, tech, health care, and travel categories, among others•Specialized experience with hands-on agency account management •Self-starter with a roll-up-your-sleeves mentality•Ability to work with the internal teams to solve problems•Solid grasp of interactive media, including various pricing models, targeting technologies, and ad serving•Bachelor's degree•Strong long-distance communication skills using email, instant messenger platforms, and phone•High technical aptitude for learning and working within desktop and web-based applications (Windows, Microsoft Office, DSPs, ad exchanges) •Ability to calculate and analyze data based on standard digital advertising cost-per metrics (CPM, CPC, CPA, etc.)•Detail-oriented with strong organizational skills and multitasking ability•Ability to work efficiently and effectively under tight deadlines; strong sense of urgency•Personality to work effectively within a fast-moving environment and with many different types of people•Desire and ability to work from home\xa0"

In [644]:
df = df[['description', 'industry']]

In [645]:
df

,description,industry
1,Organised - Focused - Vibrant - Awesome!Do you...,Marketing and Advertising
3,THE COMPANY: ESRI – Environmental Systems Rese...,Computer Software
4,JOB TITLE: Itemization Review ManagerLOCATION:...,Hospital & Health Care
9,The Customer Service Associate will be based i...,Financial Services
10,Position : DeveloperJob Location :United Stat...,Information Technology and Services
...,...,...
17872,Flite's SaaS display ad platform fuels the wor...,Internet
17874,"Sr, JavaScript Developer Experience : 4-10 yea...",Computer Software
17875,Just in case this is the first time you’ve vis...,Computer Software
17876,The Payroll Accountant will focus primarily on...,Internet
17879,Who are we?Vend is an award winning web based ...,Computer Software

In [646]:
from collections import Counter
Counter(" ".join(df['description']).split()).most_common(20)

[('and', 72024),
 ('to', 39711),
 ('the', 36302),
 ('of', 28498),
 ('a', 25500),
 ('in', 21729),
 ('for', 19390),
 ('with', 17582),
 ('our', 12559),
 ('is', 11679),
 ('will', 9481),
 ('be', 9321),
 ('are', 9051),
 ('on', 8073),
 ('as', 7391),
 ('you', 7064),
 ('an', 6508),
 ('that', 6243),
 ('team', 5796),
 ('We', 5073)]

## Cleaning from stop words

In [647]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

def remove_stopwords(text):
    return " ".join([word for word in text.split() if word.lower() not in ENGLISH_STOP_WORDS])

df['description'] = df['description'].apply(remove_stopwords)

C:\Users\Павел\AppData\Local\Temp\ipykernel_17228\2776479452.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['description'] = df['description'].apply(remove_stopwords)

In [648]:
df.iloc[4]['description']

"Position : DeveloperJob Location :United States-New Jersey-Jersey CityUs work status required : EAD / Green Card / Citizens Detailed Description Developer strong SQL &amp; VB.NET working highly effective software development team responsible development enhancements IDB reporting billing systems. work efforts performed according policies procedures relating software development quality.Background: Developer 5+ years development experience using , VB.NET, including 3-5 years SQL development.Required:• College degree• Experience building web based applications using SQL Server.• Expert level, hands-on experience writing SQL Server Stored Procedures.• Proficient MS Office products (Excel, Access, Word, Outlook)• Worked role involved creation reports internal management and/or external customers.• Experience developing scripting/front-end language.• Excellent communication skillsIf interested, send updated profile #EMAIL_897dfb1f33f6c34f2bed521623e9808aa4e62d89a6c0284cfe89393e4457e628#Hiring Sales Account Director(advertising/digital sales)Position : Sales Account Director - Pacific NorthwestJob Location : United States,Washington-SeattleUs work status required : EAD / Green Card / Citizens Requirements :•3+ years advertising/digital sales experience, preferrably region•Ability provide forecasting information management•Proven success prospecting/cold-calling regional accounts•Proven experience automotive, tech, health care, travel categories, others•Specialized experience hands-on agency account management •Self-starter roll-up-your-sleeves mentality•Ability work internal teams solve problems•Solid grasp interactive media, including various pricing models, targeting technologies, ad serving•Bachelor's degree•Strong long-distance communication skills using email, instant messenger platforms, phone•High technical aptitude learning working desktop web-based applications (Windows, Microsoft Office, DSPs, ad exchanges) •Ability calculate analyze data based standard digital advertising cost-per metrics (CPM, CPC, CPA, etc.)•Detail-oriented strong organizational skills multitasking ability•Ability work efficiently effectively tight deadlines; strong sense urgency•Personality work effectively fast-moving environment different types people•Desire ability work home"

In [649]:
Counter(" ".join(df['description']).split()).most_common(20)

[('team', 5796),
 ('work', 4912),
 ('business', 3780),
 ('new', 3758),
 ('looking', 3595),
 ('customer', 3274),
 ('sales', 3031),
 ('experience', 2829),
 ('development', 2773),
 ('product', 2611),
 ('company', 2390),
 ('marketing', 2357),
 ('&amp;', 2211),
 ('working', 2158),
 ('-', 2095),
 ('data', 2046),
 ('client', 2022),
 ('management', 1926),
 ('help', 1923),
 ('software', 1889)]

## Lowercasting

In [650]:
df['description'] = df['description'].str.lower()

C:\Users\Павел\AppData\Local\Temp\ipykernel_17228\4256182617.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['description'] = df['description'].str.lower()

## Remove extra spaces

In [651]:
df['description_clean'] = df['description'].str.replace(r'\s+', ' ', regex=True).str.strip()

C:\Users\Павел\AppData\Local\Temp\ipykernel_17228\2496257133.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['description_clean'] = df['description'].str.replace(r'\s+', ' ', regex=True).str.strip()

## Remove special charecters

In [652]:
def clean_spaces_around_punct(text):
    # Remove spaces before punctuation
    text = re.sub(r'\s+([.,!?;:])', r'\1', text)
    # Ensure exactly one space after punctuation (if not end of line)
    text = re.sub(r'([.,!?;:])([^\s])', r'\1 \2', text)
    return text.strip()

df['description'] = df['description'].apply(clean_spaces_around_punct)

C:\Users\Павел\AppData\Local\Temp\ipykernel_17228\3980907445.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['description'] = df['description'].apply(clean_spaces_around_punct)

## Lemmatization

In [653]:
import nltk
from nltk.stem import WordNetLemmatizer


lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

# Apply to your DataFrame
df['description'] = df['description'].apply(lemmatize_text)

C:\Users\Павел\AppData\Local\Temp\ipykernel_17228\2412539693.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['description'] = df['description'].apply(lemmatize_text)

# Handle punctuation

In [ ]:
import re

# Clean description: lowercase and remove non-word characters (punctuation)
df['description'] = (
    df['description']
    .fillna('')
    .astype(str)
    .apply(lambda x: ' '.join(re.findall(r'\b\w+\b', x.lower())))
)

print(df['description'].head())

1     organised focused vibrant awesome do passion c...
3     company esri environmental system research ins...
4     job title itemization review managerlocation f...
9     customer service associate based phoenix az ri...
10    position developerjob location united states n...
Name: description, dtype: object

C:\Users\Павел\AppData\Local\Temp\ipykernel_17228\732337837.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['description'] = (

## Handle empte stings

In [655]:
# Ensure descriptions are strings and strip extra spaces
df['description'] = df['description'].fillna('').astype(str).str.strip()

# Remove empty descriptions
df = df[df['description'].str.len() > 0]

# Check the number of examples
print(f"Number of examples after cleaning: {len(df)}")

Number of examples after cleaning: 7608

C:\Users\Павел\AppData\Local\Temp\ipykernel_17228\1511399741.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['description'] = df['description'].fillna('').astype(str).str.strip()

# Save data

In [656]:
X = df['description']

In [657]:
y = df['industry']

In [658]:
import os
import pandas as pd

# Path to one level above current directory
data_path = os.path.join('..', 'data')

# Ensure folder exists
os.makedirs(data_path, exist_ok=True)

# Save X and y there
pd.DataFrame({'X': X}).to_csv(os.path.join(data_path, 'X.csv'), index=False)
pd.DataFrame({'y': y}).to_csv(os.path.join(data_path, 'y.csv'), index=False)